# Используем образ Nginx для отдачи статических файлов
FROM nginx:alpine

# Копируем статические файлы фронтенда в директорию Nginx
COPY . /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Открываем порт Nginx
EXPOSE 80

# Запускаем Nginx
CMD ["nginx", "-g", "daemon off;"]